[
  {
    "id": "prt-001",
    "partnerCode": "P-1000",
    "companyName": "VoIP Partners Nordic",
    "startingDate": "2019-06-19",
    "salesRegion": "South & Central America",
    "country": "Colombia",
    "state": "",
    "contactName": "Marco Silva",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 305000,
    "annualRevenueUsd": 812000,
    "subPartnerCount": 104,
    "orderCountApprox": 142,
    "listedOnWebsite": false,
    "accountOwnerName": "Alex Chen",
    "accountOwnerEmail": "alex.chen@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2000",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-002",
    "partnerCode": "P-1001",
    "companyName": "TeleConnect Iberia",
    "startingDate": "2018-12-23",
    "salesRegion": "Scandinavia",
    "country": "Norway",
    "state": "",
    "contactName": "Ingrid Berg",
    "distributorLevel": "Silver",
    "creditLimitUsd": 161000,
    "annualRevenueUsd": 7073000,
    "subPartnerCount": 33,
    "orderCountApprox": 77,
    "listedOnWebsite": true,
    "accountOwnerName": "Jordan Lee",
    "accountOwnerEmail": "jordan.lee@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2001",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-003",
    "partnerCode": "P-1002",
    "companyName": "CloudVoice DACH",
    "startingDate": "2020-10-09",
    "salesRegion": "UK & Ireland",
    "country": "Ireland",
    "state": "",
    "contactName": "Luis García",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 370000,
    "annualRevenueUsd": 1553000,
    "subPartnerCount": 103,
    "orderCountApprox": 168,
    "listedOnWebsite": true,
    "accountOwnerName": "Sam Rivera",
    "accountOwnerEmail": "sam.rivera@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2002",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-004",
    "partnerCode": "P-1003",
    "companyName": "Unified Comms UK",
    "startingDate": "2020-12-13",
    "salesRegion": "Central Europe",
    "country": "Poland",
    "state": "",
    "contactName": "Fatima Hassan",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 235000,
    "annualRevenueUsd": 1193000,
    "subPartnerCount": 68,
    "orderCountApprox": 50,
    "listedOnWebsite": true,
    "accountOwnerName": "Morgan Blake",
    "accountOwnerEmail": "morgan.blake@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2003",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-005",
    "partnerCode": "P-1004",
    "companyName": "Atlantic PBX Group",
    "startingDate": "2021-04-08",
    "salesRegion": "DACH North",
    "country": "Germany",
    "state": "",
    "contactName": "Henrik Larsson",
    "distributorLevel": "Silver",
    "creditLimitUsd": 164000,
    "annualRevenueUsd": 5623000,
    "subPartnerCount": 9,
    "orderCountApprox": 124,
    "listedOnWebsite": false,
    "accountOwnerName": "Priya Desai",
    "accountOwnerEmail": "priya.desai@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2004",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-006",
    "partnerCode": "P-1005",
    "companyName": "Baltic Telecom Solutions",
    "startingDate": "2019-02-09",
    "salesRegion": "DACH South",
    "country": "Switzerland",
    "state": "",
    "contactName": "Yuki Tanaka",
    "distributorLevel": "Silver",
    "creditLimitUsd": 354000,
    "annualRevenueUsd": 3041000,
    "subPartnerCount": 46,
    "orderCountApprox": 76,
    "listedOnWebsite": true,
    "accountOwnerName": "Chris Okonkwo",
    "accountOwnerEmail": "chris.okonkwo@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2005",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-007",
    "partnerCode": "P-1006",
    "companyName": "Mediterranean UC",
    "startingDate": "2020-05-09",
    "salesRegion": "Eastern Europe",
    "country": "Bulgaria",
    "state": "",
    "contactName": "Diego Ruiz",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 465000,
    "annualRevenueUsd": 1520000,
    "subPartnerCount": 56,
    "orderCountApprox": 53,
    "listedOnWebsite": true,
    "accountOwnerName": "Elena Vogel",
    "accountOwnerEmail": "elena.vogel@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2006",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-008",
    "partnerCode": "P-1007",
    "companyName": "Alpine Voice Systems",
    "startingDate": "2020-09-09",
    "salesRegion": "Africa",
    "country": "Kenya",
    "state": "",
    "contactName": "Ana Popescu",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 453000,
    "annualRevenueUsd": 3781000,
    "subPartnerCount": 25,
    "orderCountApprox": 41,
    "listedOnWebsite": true,
    "accountOwnerName": "Tomasz Kowalski",
    "accountOwnerEmail": "tomasz.kowalski@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2007",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-009",
    "partnerCode": "P-1008",
    "companyName": "Pacific Ring Networks",
    "startingDate": "2019-02-15",
    "salesRegion": "United States",
    "country": "United States",
    "state": "MA",
    "contactName": "Viktor Novak",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 265000,
    "annualRevenueUsd": 6698000,
    "subPartnerCount": 56,
    "orderCountApprox": 116,
    "listedOnWebsite": true,
    "accountOwnerName": "Sofia Martins",
    "accountOwnerEmail": "sofia.martins@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2008",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-010",
    "partnerCode": "P-1009",
    "companyName": "Great Lakes UC",
    "startingDate": "2019-11-17",
    "salesRegion": "Central",
    "country": "United States",
    "state": "FL",
    "contactName": "Zara Khan",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 456000,
    "annualRevenueUsd": 7455000,
    "subPartnerCount": 82,
    "orderCountApprox": 104,
    "listedOnWebsite": true,
    "accountOwnerName": "James Whitaker",
    "accountOwnerEmail": "james.whitaker@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2009",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-011",
    "partnerCode": "P-1010",
    "companyName": "Sunbelt Communications",
    "startingDate": "2022-11-08",
    "salesRegion": "North East",
    "country": "United States",
    "state": "MA",
    "contactName": "Marco Silva",
    "distributorLevel": "Gold",
    "creditLimitUsd": 293000,
    "annualRevenueUsd": 2338000,
    "subPartnerCount": 78,
    "orderCountApprox": 176,
    "listedOnWebsite": true,
    "accountOwnerName": "Alex Chen",
    "accountOwnerEmail": "alex.chen@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2010",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-012",
    "partnerCode": "P-1011",
    "companyName": "Metro Connect France",
    "startingDate": "2019-03-01",
    "salesRegion": "South East",
    "country": "United States",
    "state": "MA",
    "contactName": "Ingrid Berg",
    "distributorLevel": "Silver",
    "creditLimitUsd": 192000,
    "annualRevenueUsd": 4233000,
    "subPartnerCount": 66,
    "orderCountApprox": 30,
    "listedOnWebsite": true,
    "accountOwnerName": "Jordan Lee",
    "accountOwnerEmail": "jordan.lee@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2011",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-013",
    "partnerCode": "P-1012",
    "companyName": "Rhine Valley IT",
    "startingDate": "2023-02-09",
    "salesRegion": "West",
    "country": "United States",
    "state": "WA",
    "contactName": "Luis García",
    "distributorLevel": "Silver",
    "creditLimitUsd": 273000,
    "annualRevenueUsd": 5651000,
    "subPartnerCount": 54,
    "orderCountApprox": 69,
    "listedOnWebsite": false,
    "accountOwnerName": "Sam Rivera",
    "accountOwnerEmail": "sam.rivera@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2012",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-014",
    "partnerCode": "P-1013",
    "companyName": "Danube Digital",
    "startingDate": "2020-05-06",
    "salesRegion": "Italy",
    "country": "Italy",
    "state": "",
    "contactName": "Fatima Hassan",
    "distributorLevel": "Silver",
    "creditLimitUsd": 338000,
    "annualRevenueUsd": 6142000,
    "subPartnerCount": 44,
    "orderCountApprox": 150,
    "listedOnWebsite": true,
    "accountOwnerName": "Morgan Blake",
    "accountOwnerEmail": "morgan.blake@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2013",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-015",
    "partnerCode": "P-1014",
    "companyName": "Caspian Telecom",
    "startingDate": "2018-11-09",
    "salesRegion": "Australiasia",
    "country": "Australia",
    "state": "",
    "contactName": "Henrik Larsson",
    "distributorLevel": "Silver",
    "creditLimitUsd": 491000,
    "annualRevenueUsd": 1791000,
    "subPartnerCount": 61,
    "orderCountApprox": 138,
    "listedOnWebsite": true,
    "accountOwnerName": "Priya Desai",
    "accountOwnerEmail": "priya.desai@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2014",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-016",
    "partnerCode": "P-1015",
    "companyName": "Red Sea Voice",
    "startingDate": "2021-10-15",
    "salesRegion": "Middle East North Aftica",
    "country": "Israel",
    "state": "",
    "contactName": "Yuki Tanaka",
    "distributorLevel": "Gold",
    "creditLimitUsd": 370000,
    "annualRevenueUsd": 487000,
    "subPartnerCount": 33,
    "orderCountApprox": 15,
    "listedOnWebsite": true,
    "accountOwnerName": "Chris Okonkwo",
    "accountOwnerEmail": "chris.okonkwo@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2015",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-017",
    "partnerCode": "P-1016",
    "companyName": "Sahara UC Partners",
    "startingDate": "2023-03-09",
    "salesRegion": "France",
    "country": "France",
    "state": "",
    "contactName": "Diego Ruiz",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 179000,
    "annualRevenueUsd": 5907000,
    "subPartnerCount": 47,
    "orderCountApprox": 59,
    "listedOnWebsite": true,
    "accountOwnerName": "Elena Vogel",
    "accountOwnerEmail": "elena.vogel@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2016",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-018",
    "partnerCode": "P-1017",
    "companyName": "Cape Town Comms",
    "startingDate": "2021-08-07",
    "salesRegion": "France North",
    "country": "France",
    "state": "",
    "contactName": "Ana Popescu",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 52000,
    "annualRevenueUsd": 1886000,
    "subPartnerCount": 68,
    "orderCountApprox": 82,
    "listedOnWebsite": true,
    "accountOwnerName": "Tomasz Kowalski",
    "accountOwnerEmail": "tomasz.kowalski@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2017",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-019",
    "partnerCode": "P-1018",
    "companyName": "Lagos Connect",
    "startingDate": "2022-09-30",
    "salesRegion": "France South",
    "country": "France",
    "state": "",
    "contactName": "Viktor Novak",
    "distributorLevel": "Gold",
    "creditLimitUsd": 381000,
    "annualRevenueUsd": 3094000,
    "subPartnerCount": 47,
    "orderCountApprox": 18,
    "listedOnWebsite": true,
    "accountOwnerName": "Sofia Martins",
    "accountOwnerEmail": "sofia.martins@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2018",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-020",
    "partnerCode": "P-1019",
    "companyName": "Nairobi Voice Hub",
    "startingDate": "2020-02-05",
    "salesRegion": "BeNeLux",
    "country": "Netherlands",
    "state": "",
    "contactName": "Zara Khan",
    "distributorLevel": "Gold",
    "creditLimitUsd": 327000,
    "annualRevenueUsd": 5299000,
    "subPartnerCount": 120,
    "orderCountApprox": 93,
    "listedOnWebsite": true,
    "accountOwnerName": "James Whitaker",
    "accountOwnerEmail": "james.whitaker@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2019",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-021",
    "partnerCode": "P-1020",
    "companyName": "Singapore Ring",
    "startingDate": "2022-01-26",
    "salesRegion": "Iberia",
    "country": "Spain",
    "state": "",
    "contactName": "Marco Silva",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 285000,
    "annualRevenueUsd": 1990000,
    "subPartnerCount": 8,
    "orderCountApprox": 51,
    "listedOnWebsite": true,
    "accountOwnerName": "Alex Chen",
    "accountOwnerEmail": "alex.chen@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2020",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-022",
    "partnerCode": "P-1021",
    "companyName": "Tokyo UC Partners",
    "startingDate": "2019-02-28",
    "salesRegion": "Canada",
    "country": "Canada",
    "state": "",
    "contactName": "Ingrid Berg",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 176000,
    "annualRevenueUsd": 6486000,
    "subPartnerCount": 7,
    "orderCountApprox": 144,
    "listedOnWebsite": true,
    "accountOwnerName": "Jordan Lee",
    "accountOwnerEmail": "jordan.lee@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2021",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-023",
    "partnerCode": "P-1022",
    "companyName": "Seoul Voice Pro",
    "startingDate": "2021-08-16",
    "salesRegion": "Asia",
    "country": "India",
    "state": "",
    "contactName": "Luis García",
    "distributorLevel": "Gold",
    "creditLimitUsd": 243000,
    "annualRevenueUsd": 3569000,
    "subPartnerCount": 33,
    "orderCountApprox": 29,
    "listedOnWebsite": true,
    "accountOwnerName": "Sam Rivera",
    "accountOwnerEmail": "sam.rivera@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2022",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-024",
    "partnerCode": "P-1023",
    "companyName": "Mumbai Telecom Hub",
    "startingDate": "2020-10-08",
    "salesRegion": "Russia",
    "country": "Russia",
    "state": "",
    "contactName": "Fatima Hassan",
    "distributorLevel": "Gold",
    "creditLimitUsd": 402000,
    "annualRevenueUsd": 3506000,
    "subPartnerCount": 53,
    "orderCountApprox": 82,
    "listedOnWebsite": true,
    "accountOwnerName": "Morgan Blake",
    "accountOwnerEmail": "morgan.blake@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2023",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-025",
    "partnerCode": "P-1024",
    "companyName": "Sydney PBX Group",
    "startingDate": "2019-10-21",
    "salesRegion": "South & Central America",
    "country": "Colombia",
    "state": "",
    "contactName": "Henrik Larsson",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 145000,
    "annualRevenueUsd": 5244000,
    "subPartnerCount": 63,
    "orderCountApprox": 150,
    "listedOnWebsite": true,
    "accountOwnerName": "Priya Desai",
    "accountOwnerEmail": "priya.desai@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2024",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-026",
    "partnerCode": "P-1025",
    "companyName": "Melbourne Voice",
    "startingDate": "2018-02-07",
    "salesRegion": "Scandinavia",
    "country": "Norway",
    "state": "",
    "contactName": "Yuki Tanaka",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 462000,
    "annualRevenueUsd": 388000,
    "subPartnerCount": 76,
    "orderCountApprox": 176,
    "listedOnWebsite": true,
    "accountOwnerName": "Chris Okonkwo",
    "accountOwnerEmail": "chris.okonkwo@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2025",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-027",
    "partnerCode": "P-1026",
    "companyName": "Auckland Connect",
    "startingDate": "2023-01-27",
    "salesRegion": "UK & Ireland",
    "country": "Ireland",
    "state": "",
    "contactName": "Diego Ruiz",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 81000,
    "annualRevenueUsd": 858000,
    "subPartnerCount": 86,
    "orderCountApprox": 19,
    "listedOnWebsite": true,
    "accountOwnerName": "Elena Vogel",
    "accountOwnerEmail": "elena.vogel@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2026",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-028",
    "partnerCode": "P-1027",
    "companyName": "Toronto UC",
    "startingDate": "2019-12-23",
    "salesRegion": "Central Europe",
    "country": "Czech Republic",
    "state": "",
    "contactName": "Ana Popescu",
    "distributorLevel": "Gold",
    "creditLimitUsd": 226000,
    "annualRevenueUsd": 1484000,
    "subPartnerCount": 28,
    "orderCountApprox": 97,
    "listedOnWebsite": true,
    "accountOwnerName": "Tomasz Kowalski",
    "accountOwnerEmail": "tomasz.kowalski@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2027",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-029",
    "partnerCode": "P-1028",
    "companyName": "Vancouver Voice",
    "startingDate": "2022-02-03",
    "salesRegion": "DACH North",
    "country": "Germany",
    "state": "",
    "contactName": "Viktor Novak",
    "distributorLevel": "Silver",
    "creditLimitUsd": 148000,
    "annualRevenueUsd": 7688000,
    "subPartnerCount": 70,
    "orderCountApprox": 160,
    "listedOnWebsite": false,
    "accountOwnerName": "Sofia Martins",
    "accountOwnerEmail": "sofia.martins@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2028",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-030",
    "partnerCode": "P-1029",
    "companyName": "Montreal Telecom",
    "startingDate": "2021-03-14",
    "salesRegion": "DACH South",
    "country": "Austria",
    "state": "",
    "contactName": "Zara Khan",
    "distributorLevel": "Silver",
    "creditLimitUsd": 497000,
    "annualRevenueUsd": 6475000,
    "subPartnerCount": 112,
    "orderCountApprox": 143,
    "listedOnWebsite": true,
    "accountOwnerName": "James Whitaker",
    "accountOwnerEmail": "james.whitaker@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2029",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-031",
    "partnerCode": "P-1030",
    "companyName": "Mexico City VoIP",
    "startingDate": "2022-07-11",
    "salesRegion": "Eastern Europe",
    "country": "Bulgaria",
    "state": "",
    "contactName": "Marco Silva",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 341000,
    "annualRevenueUsd": 5877000,
    "subPartnerCount": 80,
    "orderCountApprox": 169,
    "listedOnWebsite": true,
    "accountOwnerName": "Alex Chen",
    "accountOwnerEmail": "alex.chen@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2030",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-032",
    "partnerCode": "P-1031",
    "companyName": "São Paulo Ring",
    "startingDate": "2018-06-01",
    "salesRegion": "Africa",
    "country": "Nigeria",
    "state": "",
    "contactName": "Ingrid Berg",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 492000,
    "annualRevenueUsd": 4287000,
    "subPartnerCount": 27,
    "orderCountApprox": 145,
    "listedOnWebsite": false,
    "accountOwnerName": "Jordan Lee",
    "accountOwnerEmail": "jordan.lee@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2031",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-033",
    "partnerCode": "P-1032",
    "companyName": "Bogotá Connect",
    "startingDate": "2020-02-20",
    "salesRegion": "United States",
    "country": "United States",
    "state": "CA",
    "contactName": "Luis García",
    "distributorLevel": "Gold",
    "creditLimitUsd": 341000,
    "annualRevenueUsd": 7420000,
    "subPartnerCount": 43,
    "orderCountApprox": 123,
    "listedOnWebsite": true,
    "accountOwnerName": "Sam Rivera",
    "accountOwnerEmail": "sam.rivera@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2032",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-034",
    "partnerCode": "P-1033",
    "companyName": "Buenos Aires UC",
    "startingDate": "2023-04-05",
    "salesRegion": "Central",
    "country": "United States",
    "state": "TX",
    "contactName": "Fatima Hassan",
    "distributorLevel": "Silver",
    "creditLimitUsd": 397000,
    "annualRevenueUsd": 3649000,
    "subPartnerCount": 21,
    "orderCountApprox": 21,
    "listedOnWebsite": true,
    "accountOwnerName": "Morgan Blake",
    "accountOwnerEmail": "morgan.blake@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2033",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-035",
    "partnerCode": "P-1034",
    "companyName": "Warsaw Voice Partners",
    "startingDate": "2021-11-01",
    "salesRegion": "North East",
    "country": "United States",
    "state": "WA",
    "contactName": "Henrik Larsson",
    "distributorLevel": "Gold",
    "creditLimitUsd": 184000,
    "annualRevenueUsd": 905000,
    "subPartnerCount": 4,
    "orderCountApprox": 72,
    "listedOnWebsite": true,
    "accountOwnerName": "Priya Desai",
    "accountOwnerEmail": "priya.desai@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2034",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-036",
    "partnerCode": "P-1035",
    "companyName": "Prague Ring",
    "startingDate": "2022-12-20",
    "salesRegion": "South East",
    "country": "United States",
    "state": "CO",
    "contactName": "Yuki Tanaka",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 131000,
    "annualRevenueUsd": 5003000,
    "subPartnerCount": 103,
    "orderCountApprox": 90,
    "listedOnWebsite": true,
    "accountOwnerName": "Chris Okonkwo",
    "accountOwnerEmail": "chris.okonkwo@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2035",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-037",
    "partnerCode": "P-1036",
    "companyName": "Budapest Connect",
    "startingDate": "2023-06-12",
    "salesRegion": "West",
    "country": "United States",
    "state": "WA",
    "contactName": "Diego Ruiz",
    "distributorLevel": "Silver",
    "creditLimitUsd": 26000,
    "annualRevenueUsd": 7356000,
    "subPartnerCount": 47,
    "orderCountApprox": 151,
    "listedOnWebsite": true,
    "accountOwnerName": "Elena Vogel",
    "accountOwnerEmail": "elena.vogel@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2036",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-038",
    "partnerCode": "P-1037",
    "companyName": "Bucharest UC",
    "startingDate": "2018-11-19",
    "salesRegion": "Italy",
    "country": "Italy",
    "state": "",
    "contactName": "Ana Popescu",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 246000,
    "annualRevenueUsd": 7788000,
    "subPartnerCount": 104,
    "orderCountApprox": 122,
    "listedOnWebsite": false,
    "accountOwnerName": "Tomasz Kowalski",
    "accountOwnerEmail": "tomasz.kowalski@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2037",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-039",
    "partnerCode": "P-1038",
    "companyName": "Sofia Voice",
    "startingDate": "2020-05-07",
    "salesRegion": "Australiasia",
    "country": "New Zealand",
    "state": "",
    "contactName": "Viktor Novak",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 444000,
    "annualRevenueUsd": 3960000,
    "subPartnerCount": 72,
    "orderCountApprox": 178,
    "listedOnWebsite": false,
    "accountOwnerName": "Sofia Martins",
    "accountOwnerEmail": "sofia.martins@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2038",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-040",
    "partnerCode": "P-1039",
    "companyName": "Athens Telecom",
    "startingDate": "2021-06-05",
    "salesRegion": "Middle East North Aftica",
    "country": "Israel",
    "state": "",
    "contactName": "Zara Khan",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 280000,
    "annualRevenueUsd": 2743000,
    "subPartnerCount": 97,
    "orderCountApprox": 37,
    "listedOnWebsite": true,
    "accountOwnerName": "James Whitaker",
    "accountOwnerEmail": "james.whitaker@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2039",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-041",
    "partnerCode": "P-1040",
    "companyName": "Lisbon Ring",
    "startingDate": "2021-02-22",
    "salesRegion": "France",
    "country": "France",
    "state": "",
    "contactName": "Marco Silva",
    "distributorLevel": "Gold",
    "creditLimitUsd": 184000,
    "annualRevenueUsd": 6155000,
    "subPartnerCount": 77,
    "orderCountApprox": 72,
    "listedOnWebsite": true,
    "accountOwnerName": "Alex Chen",
    "accountOwnerEmail": "alex.chen@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2040",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-042",
    "partnerCode": "P-1041",
    "companyName": "Madrid Voice Hub",
    "startingDate": "2020-02-23",
    "salesRegion": "France North",
    "country": "France",
    "state": "",
    "contactName": "Ingrid Berg",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 318000,
    "annualRevenueUsd": 6374000,
    "subPartnerCount": 57,
    "orderCountApprox": 173,
    "listedOnWebsite": true,
    "accountOwnerName": "Jordan Lee",
    "accountOwnerEmail": "jordan.lee@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2041",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-043",
    "partnerCode": "P-1042",
    "companyName": "Brussels Connect",
    "startingDate": "2023-05-15",
    "salesRegion": "France South",
    "country": "France",
    "state": "",
    "contactName": "Luis García",
    "distributorLevel": "Silver",
    "creditLimitUsd": 423000,
    "annualRevenueUsd": 5294000,
    "subPartnerCount": 56,
    "orderCountApprox": 94,
    "listedOnWebsite": false,
    "accountOwnerName": "Sam Rivera",
    "accountOwnerEmail": "sam.rivera@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2042",
    "notes": "Focus on mid-market; strong hosting attach."
  },
  {
    "id": "prt-044",
    "partnerCode": "P-1043",
    "companyName": "Amsterdam UC",
    "startingDate": "2021-10-03",
    "salesRegion": "BeNeLux",
    "country": "Netherlands",
    "state": "",
    "contactName": "Fatima Hassan",
    "distributorLevel": "Silver",
    "creditLimitUsd": 305000,
    "annualRevenueUsd": 6474000,
    "subPartnerCount": 100,
    "orderCountApprox": 19,
    "listedOnWebsite": true,
    "accountOwnerName": "Morgan Blake",
    "accountOwnerEmail": "morgan.blake@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2043",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-045",
    "partnerCode": "P-1044",
    "companyName": "Dublin Voice",
    "startingDate": "2022-02-07",
    "salesRegion": "Iberia",
    "country": "Spain",
    "state": "",
    "contactName": "Henrik Larsson",
    "distributorLevel": "Silver",
    "creditLimitUsd": 419000,
    "annualRevenueUsd": 2268000,
    "subPartnerCount": 18,
    "orderCountApprox": 38,
    "listedOnWebsite": true,
    "accountOwnerName": "Priya Desai",
    "accountOwnerEmail": "priya.desai@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2044",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-046",
    "partnerCode": "P-1045",
    "companyName": "Glasgow Ring",
    "startingDate": "2023-03-22",
    "salesRegion": "Canada",
    "country": "Canada",
    "state": "",
    "contactName": "Yuki Tanaka",
    "distributorLevel": "Silver",
    "creditLimitUsd": 457000,
    "annualRevenueUsd": 5930000,
    "subPartnerCount": 28,
    "orderCountApprox": 178,
    "listedOnWebsite": true,
    "accountOwnerName": "Chris Okonkwo",
    "accountOwnerEmail": "chris.okonkwo@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2045",
    "notes": "Renewal-heavy region; proactive QBRs recommended."
  },
  {
    "id": "prt-047",
    "partnerCode": "P-1046",
    "companyName": "Manchester Connect",
    "startingDate": "2021-09-06",
    "salesRegion": "Asia",
    "country": "India",
    "state": "",
    "contactName": "Diego Ruiz",
    "distributorLevel": "Silver",
    "creditLimitUsd": 267000,
    "annualRevenueUsd": 2689000,
    "subPartnerCount": 64,
    "orderCountApprox": 155,
    "listedOnWebsite": true,
    "accountOwnerName": "Elena Vogel",
    "accountOwnerEmail": "elena.vogel@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2046",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-048",
    "partnerCode": "P-1047",
    "companyName": "Edinburgh UC",
    "startingDate": "2019-04-10",
    "salesRegion": "Russia",
    "country": "Russia",
    "state": "",
    "contactName": "Ana Popescu",
    "distributorLevel": "Platinum",
    "creditLimitUsd": 248000,
    "annualRevenueUsd": 4137000,
    "subPartnerCount": 101,
    "orderCountApprox": 32,
    "listedOnWebsite": true,
    "accountOwnerName": "Tomasz Kowalski",
    "accountOwnerEmail": "tomasz.kowalski@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2047",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-049",
    "partnerCode": "P-1048",
    "companyName": "Oslo Voice",
    "startingDate": "2021-07-23",
    "salesRegion": "South & Central America",
    "country": "Mexico",
    "state": "",
    "contactName": "Viktor Novak",
    "distributorLevel": "Gold",
    "creditLimitUsd": 47000,
    "annualRevenueUsd": 6687000,
    "subPartnerCount": 71,
    "orderCountApprox": 99,
    "listedOnWebsite": false,
    "accountOwnerName": "Sofia Martins",
    "accountOwnerEmail": "sofia.martins@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2048",
    "notes": "Standard partner health; quarterly business reviews."
  },
  {
    "id": "prt-050",
    "partnerCode": "P-1049",
    "companyName": "Stockholm Ring",
    "startingDate": "2021-02-26",
    "salesRegion": "Scandinavia",
    "country": "Norway",
    "state": "",
    "contactName": "Zara Khan",
    "distributorLevel": "Gold",
    "creditLimitUsd": 154000,
    "annualRevenueUsd": 1767000,
    "subPartnerCount": 93,
    "orderCountApprox": 148,
    "listedOnWebsite": true,
    "accountOwnerName": "James Whitaker",
    "accountOwnerEmail": "james.whitaker@3cx-sales.example",
    "accountOwnerPhone": "+1-555-2049",
    "notes": "Focus on mid-market; strong hosting attach."
  }
]